---
settings:
  name: Active IQ Unified Manager 9.10
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.10'
    url: "/active-iq-unified-manager-910"
  - version-number: '9.14'
    url: "/active-iq-unified-manager"
  - version-number: '9.13'
    url: "/active-iq-unified-manager-913"
  - version-number: '9.12'
    url: "/active-iq-unified-manager-912"
  - version-number: '9.11'
    url: "/active-iq-unified-manager-911"
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.10 Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/reference_release_notes.html"
  - title: Los geht's
    entries:
    - title: Schnellstartinstallation für VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/install-linux/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
