---
settings:
  name: Active IQ Unified Manager 9.10
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager
    url: "/active-iq-unified-manager-910"
    version-number: '9.10'
  - name: Unified Manager
    url: "/active-iq-unified-manager"
    version-number: '9.13'
  - name: Unified Manager
    url: "/active-iq-unified-manager-912"
    version-number: '9.12'
  - name: Unified Manager
    url: "/active-iq-unified-manager-911"
    version-number: '9.11'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.10 Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/reference_release_notes.html"
  - title: Los geht's
    entries:
    - title: Schnellstartinstallation für VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/install-linux/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Produktübersicht
      url: "/storage-mgmt/concept_introduction_to_unified_manager.html"
    - title: Versionshinweise
      url: reference_release_notes.html
    - title: Schnellstartinstallation für VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/install-linux/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/install-windows/qsg-windows.html"
  - title: Installation Konfiguration von Unified Manager
    links:
    - title: Installieren Sie das Upgrade auf VMware vSphere Systemen
      url: "/install-vapp/concept_requirements_for_installing_unified_manager.html"
    - title: Upgrade auf Linux-Systemen installieren
      url: "/install-linux/concept_requirements_for_install_unified_manager.html"
    - title: Installieren Sie das Upgrade auf Windows-Systemen
      url: "/install-windows/concept_requirements_for_installing_unified_manager.html"
    - title: Konfiguration Von Unified Manager
      url: "/config/concept_configure_unified_manager.html"
    - title: Funktionseinstellungen verwalten
      url: "/config/concept_manage_feature_settings.html"
    - title: Management von rollenbasiertem Zugriff
      url: "/config/concept_manage_user_access.html"
  - title: Performance Monitoring
    links:
    - title: Performance-Schwellenwerte
      url: "/performance-checker/concept_manage_performance_thresholds.html"
    - title: Cluster-Performance
      url: "/performance-checker/concept_monitor_cluster_performance_from_dashboard.html"
    - title: QoS-Richtliniengruppe
      url: "/performance-checker/concept_manage_performance_using_qos_policy_group_information.html"
    - title: Workload Analyzer
      url: "/performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html"
    - title: Workload-Performance
      url: "/performance-checker/concept_collect_data_and_monitor_workload_performance.html"
    - title: Performance-Management
      url: "/performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html"
  - title: Monitoring des Storage- und Objektstatus
    links:
    - title: Workloads
      url: "/storage-mgmt/concept_provision_and_manage_workloads.html"
    - title: Virtuelle Infrastruktur
      url: "/storage-mgmt/concept_monitor_vmware_virtual_infrastructure.html"
    - title: MetroCluster Konfigurationen
      url: "/storage-mgmt/concept_manage_and_monitor_metrocluster_configurations.html"
    - title: Cluster und Cluster-Objektstatus
      url: "/health-checker/concept_manage_and_monitor_clusters_and_cluster_object_health.html"
    - title: Systemzustandsschwellenwerte
      url: "/health-checker/concept_manage_health_thresholds.html"
    - title: Senden Sie AutoSupport-Meldungen und Support-Bundles
      url: "/health-checker/task_send_asup_to_technical_support.html"
  - title: Monitoring der Datensicherung
    links:
    - title: Sicherungsbeziehung einrichten
      url: "/data-protection/task_set_up_protection_relationships_in_unified_manager.html"
    - title: Führen Sie Failover und Failback durch
      url: "/data-protection/task_perform_protection_relationship_failover_and_failback.html"
    - title: Sicherungsbeziehung managen
      url: "/data-protection/concept_manage_and_monitor_protection_relationships.html"
    - title: Überwachen von Disaster-Recovery-Beziehungen
      url: "/data-protection/task_monitor_storage_vms_using_relationships_page.html"
    - title: Berichte generieren
      url: "/reporting/concept_unified_manager_reporting.html"
  - title: Verwendung VON REST-APIs
    links:
    - title: Los geht's
      url: "/api-automation/concept_api_url_and_categories.html"
    - title: Greifen Sie auf Unified Manager-APIs zu
      url: "/api-automation/concept_rest_api_access_and_authentication_in_um_apis.html"
    - title: Management von Storage-Objekten
      url: "/api-automation/concept_data_center_apis.html"
    - title: Greifen Sie auf ONTAP-APIs zu
      url: "/api-automation/concept_gateway_apis.html"
    - title: Typische Workflows
      url: "/api-automation/concept_workflow_intro.html"
    - title: Bereitstellung von Storage
      url: "/api-automation/concept_provision_workflow.html"
  - title: Ereignisse und Meldungen
    links:
    - title: Dashboard
      url: "/storage-mgmt/reference_dashboard_page.html"
    - title: Ereignis-Workflow
      url: "/events/concept_what_happens_when_an_event_is_received.html"
    - title: Plattform-Events der Active IQ Serie
      url: "/events/concept_how_active_iq_platform_events_are_generated.html"
    - title: Ereignisse und Schweregrade
      url: "/events/reference_list_of_events_and_severity_types.html"
    - title: Ereignisse zur Korrektur
      url: "/storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html"
    - title: Automatische Korrektur
      url: "/storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html"
  - title: Mehr Ressourcen
    links:
    - title: Unified Manager Videos
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager Blogs
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Dokumentation für Active IQ Unified Manager 9.9 oder früher
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62791
