---
permalink: api-automation/concept_manage_access_endpoint.html 
sidebar: sidebar 
keywords: manage, endpoints, access 
summary: 'Zugriffendpunkte oder logische Schnittstellen (LIFs) müssen erstellt werden, die für die Bereitstellung von Storage Virtual Machines (SVMs), LUNs und Dateifreigaben erforderlich sind. Sie können die Zugriffendpunkte für die SVMs, LUNs oder File Shares in der Active IQ Unified Manager Umgebung anzeigen, erstellen, ändern und löschen.' 
---
= Management von Zugriffendpunkten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zugriffendpunkte oder logische Schnittstellen (LIFs) müssen erstellt werden, die für die Bereitstellung von Storage Virtual Machines (SVMs), LUNs und Dateifreigaben erforderlich sind. Sie können die Zugriffendpunkte für die SVMs, LUNs oder File Shares in der Active IQ Unified Manager Umgebung anzeigen, erstellen, ändern und löschen.



== Zugriffendpunkte anzeigen

Sie können eine Liste der Zugriffendpunkte in Ihrer Unified Manager-Umgebung mithilfe der folgenden Methode anzeigen. Um eine Liste der Zugriffendpunkte einer bestimmten SVM, LUN oder Dateifreigabe abzufragen, müssen Sie die eindeutige Kennung für die SVM, die LUN oder die Dateifreigabe eingeben. Sie können auch die eindeutige Taste für den Zugriffendpunkt eingeben, um die Details des jeweiligen Zugriffendpunkts abzurufen.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
GET
 a| 
`/storage-provider/access-endpoints`

`/storage-provider/access-endpoints/\{key}`

|===


== Fügen Sie Zugriffendpunkte hinzu

Sie können benutzerdefinierte Zugriffendpunkte erstellen und erforderliche Eigenschaften ihm zuweisen. Sie müssen die Details des Zugriffendpunkts eingeben, den Sie als Eingabeparameter erstellen möchten. Sie können diese API oder die System Manager- oder ONTAP-CLI verwenden, um auf jedem Node einen Zugriffsknoten zu erstellen. Für die Erstellung von Zugriffendpunkten werden sowohl IPv4- als auch IPv6-Adressen unterstützt.

[NOTE]
====
Sie müssen Ihre SVM für die erfolgreiche Bereitstellung von LUNs und Dateifreigaben mit einer Mindestanzahl an Zugriffendpunkten pro Node konfigurieren. Sie sollten Ihre SVM mit mindestens zwei Zugriffendpunkten pro Node konfigurieren, die jeweils ein CIFS- und/oder NFS-Protokoll unterstützen, ein weiteres iSCSI- oder FCP-Protokoll.

====
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
POST
 a| 
`/storage-provider/access-endpoints`

|===


== Zugriffsendpunkte löschen

Sie können einen bestimmten Zugriffendpunkt mithilfe der folgenden Methode löschen. Zum Löschen eines bestimmten Zugriffsparameters muss der Schlüssel für den Zugriffendpunkt als Eingabeparameter bereitgestellt werden.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
Löschen
 a| 
`/storage-provider/access-endpoints/\{key}`

|===


== Zugriffsendpunkte ändern

Sie können einen Zugriffendpunkt ändern und seine Eigenschaften mithilfe der folgenden Methode aktualisieren. Zur Änderung eines bestimmten Zugriffendpunkts müssen Sie den Schlüssel für den Zugriffendpunkt angeben. Sie müssen außerdem die Eigenschaft eingeben, die Sie aktualisieren möchten, zusammen mit ihrem Wert.

[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
PATCH
 a| 
`/storage-provider/access-endpoints/\{key}`

|===