---
permalink: api-automation/concept_verify_svm_workflow.html 
sidebar: sidebar 
keywords: verify, svms, clusters 
summary: 'Bevor Sie Dateifreigaben oder LUNs bereitstellen, müssen Sie überprüfen, ob auf den Clustern Storage Virtual Machines (SVMs) erstellt wurden.' 
---
= Überprüfung von SVMs auf Clustern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Dateifreigaben oder LUNs bereitstellen, müssen Sie überprüfen, ob auf den Clustern Storage Virtual Machines (SVMs) erstellt wurden.

[NOTE]
====
Beim Workflow wird vorausgesetzt, dass ONTAP Cluster zu Unified Manager hinzugefügt wurden und der Clusterschlüssel erhalten wurde. Auf Clustern sollten die erforderlichen Lizenzen zur Bereitstellung von LUNs und File Shares vorhanden sein.

====
. Überprüfen, ob auf dem Cluster eine SVM erstellt wurde.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Rechenzentrum
 a| 
GET
 a| 
`/datacenter/svm/svms`
`/datacenter/svm/svms/\{key}`

|===
+
*Stichprobe*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. Erstellen Sie die SVM, falls der SVM-Schlüssel nicht zurückgegeben wird. Zum Erstellen der SVMs benötigen Sie den Cluster-Schlüssel, für den Sie die SVM bereitstellen. Sie müssen außerdem den SVM-Namen angeben. Auszuführende Schritte:
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Rechenzentrum
 a| 
GET
 a| 
`/datacenter/cluster/clusters`
`/datacenter/cluster/clusters/\{key}`

|===
+
Abrufen des Cluster-Schlüssels.

+
*Stichprobe*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. Holen Sie den Cluster-Schlüssel von der Ausgabe, und verwenden Sie ihn als Input für die Erstellung der SVM.
+
[NOTE]
====
Vergewissern Sie sich bei der Erstellung der SVM, dass sie alle Protokolle unterstützt, die für die Bereitstellung von LUNs und File Shares benötigt werden, zum Beispiel CIFS, NFS, FCP Und iSCSI. Die Bereitstellungs-Workflows können fehlschlagen, wenn die SVM die erforderlichen Services nicht unterstützt. Es wird empfohlen, auch die Services für die jeweiligen Workload-Typen auf der SVM zu aktivieren.

====
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Rechenzentrum
 a| 
POST
 a| 
`/datacenter/svm/svms`

|===
+
*Stichprobe*

+
Geben Sie die Details des SVM-Objekts als Eingabeparameter ein.

+
[listing]
----
curl -X POST "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" "{ \"aggregates\": [ { \"_links\": {}, \"key\": \"1cd8a442-86d1,type=objecttype,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\",
\"name\": \"cluster2\", \"uuid\": \"02c9e252-41be-11e9-81d5-00a0986138f7\" } ],
\"cifs\": { \"ad_domain\": { \"fqdn\": \"string\", \"password\": \"string\",
\"user\": \"string\" }, \"enabled\": true, \"name\": \"CIFS1\" },
\"cluster\": { \"key\": \"1cd8a442-86d1-11e0-ae1c-123478563412,type=object type,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\" },
\"dns\": { \"domains\": [ \"example.com\", \"example2.example3.com\" ],
\"servers\": [ \"10.224.65.20\", \"2001:db08:a0b:12f0::1\" ] },
\"fcp\": { \"enabled\": true }, \"ip_interface\": [ { \"enabled\": true,
\"ip\": { \"address\": \"10.10.10.7\", \"netmask\": \"24\" },
\"location\": { \"home_node\": { \"name\": \"node1\" } }, \"name\":
\"dataLif1\" } ], \"ipspace\": { \"name\": \"exchange\" },
\"iscsi\": { \"enabled\": true }, \"language\": \"c.utf_8\",
\"ldap\": { \"ad_domain\": \"string\", \"base_dn\": \"string\",
\"bind_dn\": \"string\", \"enabled\": true, \"servers\": [ \"string\" ] },
\"name\": \"svm1\", \"nfs\": { \"enabled\": true },
\"nis\": { \"domain\": \"string\", \"enabled\": true,
\"servers\": [ \"string\" ] }, \"nvme\": { \"enabled\": true },
\"routes\": [ { \"destination\": { \"address\": \"10.10.10.7\",
\"netmask\": \"24\" }, \"gateway\": \"string\" } ],
\"snapshot_policy\": { \"name\": \"default\" },
\"state\": \"running\", \"subtype\": \"default\"}"
----
+
Die JSON-Ausgabe zeigt einen Objektschlüssel an, mit dem Sie die von Ihnen erstellte SVM überprüfen können.

. Überprüfen Sie die SVM-Erstellung mithilfe des Jobobjektschlüssels für die Abfrage. Wenn die SVM erfolgreich erstellt wurde, wird der SVM-Schlüssel in der Antwort zurückgegeben.
+
[cols="3*"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Management-Server
 a| 
GET
 a| 
`/management-server/jobs/\{key}`

|===

