---
permalink: reporting/generaltask_um_rest_apis_that_can_be_used_for_reporting.html 
sidebar: sidebar 
keywords: unified manager ,rest api, reporting 
summary: Über REST-APIs können Sie Ihre Cluster managen, indem Sie die von Unified Manager erfassten Daten zu Zustand, Kapazität, Performance und Sicherheit abrufen. 
---
= Unified Manager REST-APIs, die für die Berichterstellung verwendet werden können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über REST-APIs können Sie Ihre Cluster managen, indem Sie die von Unified Manager erfassten Daten zu Zustand, Kapazität, Performance und Sicherheit abrufen.

REST-APIs sind über die Swagger Webseite zugänglich. Sie können auf die Swagger-Webseite zugreifen, um die Rest-API-Dokumentation von Unified Manager anzuzeigen und einen API-Aufruf manuell zu tätigen. Klicken Sie in der Web-UI von Unified Manager in der Menüleiste auf die Schaltfläche *Hilfe* und wählen Sie dann *API-Dokumentation* aus. Informationen zu Unified Manager REST-APIs finden Sie im link:../api-automation/concept_get_started_with_um_apis.html["Erste Schritte mit Active IQ Unified Manager REST APIs"].

Sie müssen über die Operator-, Storage Administrator- oder Anwendungsadministratorrolle verfügen, um auf DIE REST-APIs zuzugreifen.
