---
permalink: performance-checker/concept_um_interfaces_used_to_manage_storage_system_performance.html 
sidebar: sidebar 
keywords: unified manager, interfaces, used, manage, storage, system, performance, web ui, maintenance, console 
summary: 'Active IQ Unified Manager bietet zwei Benutzeroberflächen für das Monitoring und Troubleshooting von Storage-Performance-Problemen: Die Web-Benutzeroberfläche und die Wartungskonsole.' 
---
= Unified Manager-Schnittstellen zum Management der Storage-Systemperformance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager bietet zwei Benutzeroberflächen für das Monitoring und Troubleshooting von Storage-Performance-Problemen: Die Web-Benutzeroberfläche und die Wartungskonsole.



== Unified Manager Web-UI

Die Web-UI von Unified Manager ermöglicht Administratoren das Überwachen und Beheben von Performance-bezogenen Storage-Problemen.

In diesen Abschnitten werden einige gängige Workflows beschrieben, die ein Administrator zur Behebung von Problemen hinsichtlich der Storage-Performance in der Weboberfläche von Unified Manager befolgen kann.



== Wartungskonsole

Die Wartungskonsole ermöglicht einem Administrator, Betriebssystemprobleme, Probleme mit dem Versionsaufrüstungs-, Benutzer-Zugriffsprobleme und Netzwerkprobleme im Zusammenhang mit dem Unified Manager Server selbst zu überwachen, zu diagnostizieren und zu beheben. Wenn die Web-UI von Unified Manager nicht verfügbar ist, stellt die Wartungskonsole die einzige Zugriffsmöglichkeit auf Unified Manager dar.

Diese Abschnitte geben eine Anleitung für den Zugriff auf die Wartungskonsole und deren Verwendung zur Behebung von Problemen im Zusammenhang mit der Funktionsweise des Unified Manager-Servers.
