---
permalink: performance-checker/concept_add_disks_and_perform_aggregate_layout_reconstruction.html 
sidebar: sidebar 
keywords: add, disks, perform, aggregate, layout, reconstruction 
summary: Sie können einem Aggregat Festplatten hinzufügen, um die Storage-Kapazität und Performance dieses Aggregats zu erhöhen. Nach dem Hinzufügen der Platten sehen Sie nur eine Verbesserung der Performance nach dem Rekonstruieren des Aggregats. 
---
= Fügen Sie Festplatten hinzu und führen Sie die Rekonstruktion des Aggregat-Layouts durch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einem Aggregat Festplatten hinzufügen, um die Storage-Kapazität und Performance dieses Aggregats zu erhöhen. Nach dem Hinzufügen der Platten sehen Sie nur eine Verbesserung der Performance nach dem Rekonstruieren des Aggregats.

Wenn Sie auf der Seite Ereignisdetails ein systemdefiniertes Schwellenwertereignis erhalten, enthält der Text für die Ereignisbeschreibung den Namen des Aggregats, dessen Problem aufgetreten ist. Sie können in diesem Aggregat Festplatten hinzufügen und Daten rekonstruieren.

Die Festplatten, die Sie dem Aggregat hinzufügen, müssen bereits im Cluster vorhanden sein. Wenn auf dem Cluster keine zusätzlichen Festplatten verfügbar sind, müssen Sie sich möglicherweise an den Administrator wenden oder weitere Festplatten erwerben. Mit ONTAP System Manager oder den ONTAP-Befehlen können Sie einem Aggregat Festplatten hinzufügen.

https://www.netapp.com/pdf.html?item=/media/19675-tr-3838.pdf["Technischer Bericht 3838: Konfigurationsleitfaden Für Storage-Subsysteme"^]
