---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: 'Sie können eine Richtliniengruppe für Quality of Service (QoS) erstellen, um das I/O-Limit (IOPS) oder das Durchsatzlimit (MB/s) für die in ihm enthaltenen Workloads zu steuern. Wenn sich die Workloads in einer Richtliniengruppe ohne festgelegte Grenzwerte befinden, wie z. B. in der Standardrichtlinie, oder das festgelegte Limit Ihren Anforderungen nicht entspricht, können Sie die Obergrenze erhöhen oder die Workloads in eine neue oder vorhandene Richtliniengruppe verschieben, die das gewünschte Limit hat.' 
---
= Kontrolle des Workload-Durchsatzes durch Storage-QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Richtliniengruppe für Quality of Service (QoS) erstellen, um das I/O-Limit (IOPS) oder das Durchsatzlimit (MB/s) für die in ihm enthaltenen Workloads zu steuern. Wenn sich die Workloads in einer Richtliniengruppe ohne festgelegte Grenzwerte befinden, wie z. B. in der Standardrichtlinie, oder das festgelegte Limit Ihren Anforderungen nicht entspricht, können Sie die Obergrenze erhöhen oder die Workloads in eine neue oder vorhandene Richtliniengruppe verschieben, die das gewünschte Limit hat.

„`herkömmliche`“ QoS-Richtliniengruppen können einzelnen Workloads zugewiesen werden, zum Beispiel einzelnen Volumes oder LUNs. In diesem Fall kann der Workload das volle Durchsatzlimit verwenden. QoS-Richtliniengruppen können auch mehreren Workloads zugewiesen werden. In diesem Fall ist das Durchsatzlimit zwischen den Workloads „`srot`“. Beispielsweise würde ein QoS-Limit von 9,000 IOPS, das drei Workloads zugewiesen ist, die kombinierten IOPS von über 9,000 IOPS einschränken.

„`Adaptive`“ QoS-Richtliniengruppen können auch einzelnen Workloads oder mehreren Workloads zugewiesen werden. Allerdings erhält jeder Workload bei der Zuweisung zu mehreren Workloads das volle Durchsatzlimit, anstatt gemeinsam mit anderen Workloads auf den Durchsatzwert zu zugreifen. Zudem passen anpassungsfähige QoS-Richtlinien die Durchsatzeinstellung automatisch basierend auf der Volume-Größe pro Workload an. So erhält das Verhältnis von IOPS zu Terabyte bei sich änderender Volume aufrecht. Wenn der Spitzenwert beispielsweise auf 5,000 IOPS/TB in einer anpassungsfähigen QoS-Richtlinie festgelegt wurde, hat ein 10-TB-Volume einen Durchsatz von maximal 50,000 IOPS. Wenn die Größe des Volumes später auf 20 TB geändert wird, passt die anpassungsfähige QoS das Maximum auf 100,000 IOPS an.

Ab ONTAP 9.5 können Sie die Blockgröße einschließen, wenn Sie eine anpassungsfähige QoS-Richtlinie definieren. Dadurch wird die Richtlinie in Fällen, in denen Workloads sehr große Blockgrößen verwenden und letztendlich einen hohen Prozentsatz des Durchsatzes nutzen, effektiv von einem IOPS/TB-Schwellenwert in einen MB/s-Schwellenwert konvertiert.

Wenn bei QoS-Richtlinien für Shared-Gruppen die IOPS oder MB/s aller Workloads in einer Richtliniengruppe das festgelegte Limit überschreitet, drosselt die Richtliniengruppe die Workloads, um ihre Aktivitäten zu beschränken. Dies kann die Performance aller Workloads in der Richtliniengruppe beeinträchtigen. Wenn ein dynamisches Performanceereignis durch die Richtliniengruppendrosselung generiert wird, wird in der Ereignisbeschreibung der Name der beteiligten Richtliniengruppe angezeigt.

In der Ansicht „Performance: Alle Volumes“ können die betroffenen Volumes nach IOPS und MB/s sortiert werden, um zu ermitteln, welche Workloads die höchste Auslastung aufweisen und welche dazu möglicherweise beigetragen haben. Auf der Seite „Performance/Volumes Explorer“ können Sie andere Volumes oder LUNs auf dem Volume auswählen, um sie mit den betroffenen Workload-IOPS oder der Durchsatzrate pro Sekunde zu vergleichen.

Durch die Zuweisung von Workloads, die die Node-Ressourcen zu einer restriktiveren Richtliniengruppeneinstellung überbeanspruchen, drosselt die Richtliniengruppe die Workloads, um ihre Aktivitäten zu beschränken. Dadurch wird die Nutzung der Ressourcen auf diesem Node verringert. Wenn der Workload jedoch mehr Node-Ressourcen nutzen soll, kann der Wert der Richtliniengruppe erhöht werden.

Sie können System Manager, die ONTAP-Befehle oder Unified Manager Performance Service Level verwenden, um Richtliniengruppen zu managen, einschließlich der folgenden Aufgaben:

* Erstellen einer Richtliniengruppe
* Hinzufügen oder Entfernen von Workloads in einer Richtliniengruppe
* Verschieben eines Workloads zwischen Richtliniengruppen
* Ändern der Durchsatzbegrenzung einer Richtliniengruppe
* Workloads werden in ein anderes Aggregat und/oder Node verschoben

