---
permalink: performance-checker/reference_performance_event_severity_types.html 
sidebar: sidebar 
keywords: performance, event, severity, types 
summary: Jedes Performance-Ereignis ist mit einem Schweregrad verknüpft, der Ihnen dabei hilft, die Ereignisse zu priorisieren, die unmittelbare Korrekturmaßnahmen erfordern. 
---
= Arten von Schweregrad für Performance-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jedes Performance-Ereignis ist mit einem Schweregrad verknüpft, der Ihnen dabei hilft, die Ereignisse zu priorisieren, die unmittelbare Korrekturmaßnahmen erfordern.

* * Kritisch*
+
Ein Performance-Ereignis, das zu einer Serviceunterbrechung führen kann, wenn keine Korrekturmaßnahmen sofort ergriffen werden.

+
Kritische Ereignisse werden nur von benutzerdefinierten Schwellenwerten gesendet.

* *Warnung*
+
Ein Performance-Zähler für ein Cluster-Objekt befindet sich außerhalb des normalen Bereichs und sollte überwacht werden, um sicherzustellen, dass es den kritischen Schweregrad nicht erreicht. Ereignisse dieses Schweregrades führen nicht zu einer Serviceunterbrechung und unmittelbare Korrekturmaßnahmen sind möglicherweise nicht erforderlich.

+
Warnereignisse werden von benutzerdefinierten, systemdefinierten oder dynamischen Schwellenwerten gesendet.

* *Information*
+
Das Ereignis tritt auf, wenn ein neues Objekt erkannt wird oder wenn eine Benutzeraktion durchgeführt wird. Beispiel: Wenn ein Storage-Objekt gelöscht wird oder wenn Konfigurationsänderungen vorliegen, wird das Ereignis mit dem Schweregrad „Informationen“ generiert.

+
Informationsereignisse werden direkt von ONTAP gesendet, wenn eine Konfigurationsänderung erkannt wird.



Weitere Informationen finden Sie unter den folgenden Links:

* link:../events/concept_what_happens_when_an_event_is_received.html["Was passiert, wenn ein Ereignis empfangen wird"]
* link:../events/concept_what_information_is_contained_in_an_alert_email.html["Welche Informationen sind in einer Alarm-E-Mail enthalten"]
* link:../events/task_add_alerts.html["Hinzufügen von Meldungen"]
* link:../events/task_add_alerts_for_performance_events.html["Hinzufügen von Meldungen für Performance-Ereignisse"]

