---
permalink: performance-checker/task_change_counter_charts_focus_to_smaller_period_of_time.html 
sidebar: sidebar 
keywords: change, counter, charts, focus, shorter, period, time 
summary: Mit der Maus können Sie den Zeitbereich reduzieren, um sich auf einen bestimmten Zeitraum im Bereich Zählerdiagramm oder im Fenster Zoomansicht der Zählerdiagramme zu konzentrieren. So sehen Sie eine granularere und mikroskopische Ansicht aller Teile der Zeitachse von Performance-Daten, Ereignissen und Schwellenwerten. 
---
= Ändern des Fokus der Zählerdiagramme auf einen kürzeren Zeitraum
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Maus können Sie den Zeitbereich reduzieren, um sich auf einen bestimmten Zeitraum im Bereich Zählerdiagramm oder im Fenster Zoomansicht der Zählerdiagramme zu konzentrieren. So sehen Sie eine granularere und mikroskopische Ansicht aller Teile der Zeitachse von Performance-Daten, Ereignissen und Schwellenwerten.

*Was Sie brauchen*

Der Cursor muss in eine Lupe geändert werden, um anzuzeigen, dass diese Funktion aktiv ist.

[NOTE]
====
Bei Verwendung dieser Funktion, die die Zeitleiste so ändert, dass Werte angezeigt werden, die der detaillierteren Anzeige entsprechen, ändert sich der Zeit- und Datumsbereich im Auswahlfeld *Zeitbereich* nicht von den ursprünglichen Werten für das Diagramm.

====
.Schritte
. Um einen bestimmten Zeitraum anzuzeigen, klicken Sie auf die Lupe und ziehen Sie die Maus, um den Bereich hervorzuheben, den Sie im Detail sehen möchten.
+
Die Zählerwerte für den ausgewählten Zeitraum füllen das Zählerdiagramm aus.

. Um zum ursprünglichen Zeitabschnitt zurückzukehren, der im Auswahlfeld *Zeitbereich* festgelegt wurde, klicken Sie auf die Schaltfläche *Diagrammzoom zurücksetzen*.
+
Das Zählerdiagramm wird im Originalzustand angezeigt.


