---
permalink: health-checker/concept_how_scripts_work_with_alerts.html 
sidebar: sidebar 
keywords: scripts, work, alerts 
summary: Sie können eine Warnung mit Ihrem Skript verknüpfen, damit das Skript ausgeführt wird, wenn eine Warnung für ein Ereignis in Unified Manager ausgegeben wird. Sie können die Skripte verwenden, um Probleme mit Speicherobjekten zu lösen oder zu identifizieren, welche Speicherobjekte die Ereignisse generieren. 
---
= Funktionsweise von Skripten mit Warnmeldungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Warnung mit Ihrem Skript verknüpfen, damit das Skript ausgeführt wird, wenn eine Warnung für ein Ereignis in Unified Manager ausgegeben wird. Sie können die Skripte verwenden, um Probleme mit Speicherobjekten zu lösen oder zu identifizieren, welche Speicherobjekte die Ereignisse generieren.

Wenn eine Warnung für ein Ereignis in Unified Manager generiert wird, wird eine Alarm-E-Mail an die angegebenen Empfänger gesendet. Wenn Sie einem Skript eine Warnung zugeordnet haben, wird das Skript ausgeführt. Die Details der Argumente, die an das Skript übergeben werden, können Sie aus der Alarm-E-Mail erhalten.

[NOTE]
====
Wenn Sie ein benutzerdefiniertes Skript erstellt und mit einer Warnung für einen bestimmten Ereignistyp verknüpft haben, werden Aktionen basierend auf Ihrem benutzerdefinierten Skript für diesen Ereignistyp ausgeführt, und die Aktionen *Fix it* sind auf der Seite „Management Actions“ oder im Unified Manager Dashboard standardmäßig nicht verfügbar.

====
Das Skript verwendet die folgenden Argumente zur Ausführung:

* `-eventID`
* `-eventName`
* `-eventSeverity`
* `-eventSourceID`
* `-eventSourceName`
* `-eventSourceType`
* `-eventState`
* `-eventArgs`


Sie können die Argumente in Ihren Skripten verwenden, um verwandte Ereignisinformationen zu erfassen oder Speicherobjekte zu ändern.



== Beispiel zum Abrufen von Argumenten aus Skripts

[listing]
----
print "$ARGV[0] : $ARGV[1]\n"
print "$ARGV[7] : $ARGV[8]\n"
----
Wenn eine Warnung erzeugt wird, wird dieses Skript ausgeführt und die folgende Ausgabe angezeigt:

[listing]
----
-eventID : 290
-eventSourceID : 4138
----