---
permalink: health-checker/reference_description_of_predefined_annotation_values.html 
sidebar: sidebar 
keywords: description, predefined, annotation values 
summary: Die Datenpriorität ist eine vordefinierte Annotation mit den Werten „Mission Critical“, „High“ und „Low“. Mit diesen Werten können Sie Storage-Objekte anhand der Priorität der enthaltenen Daten annotieren. Sie können die vordefinierten Anmerkungswerte nicht bearbeiten oder löschen. 
---
= Beschreibung der vordefinierten Anmerkungswerte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*Data-Priority* ist eine vordefinierte Anmerkung mit den Werten Mission Critical, High und Low. Mit diesen Werten können Sie Storage-Objekte anhand der Priorität der enthaltenen Daten annotieren. Sie können die vordefinierten Anmerkungswerte nicht bearbeiten oder löschen.

* *Datenpriorität:unternehmenskritisch*
+
Diese Annotation wird auf Storage-Objekte angewendet, die geschäftskritische Daten enthalten. Objekte mit Produktionsapplikationen können beispielsweise als unternehmenskritisch angesehen werden.

* *Datenpriorität:hoch*
+
Diese Annotation wird auf Storage-Objekte angewendet, die Daten mit hoher Priorität enthalten. Objekte, die Business-Applikationen hosten, gelten beispielsweise als hohe Priorität.

* *Datenpriorität:Niedrig*
+
Diese Annotation wird auf Storage-Objekte angewendet, die Daten mit niedriger Priorität enthalten. Beispielsweise sind Objekte, die sich auf sekundärem Storage befinden, wie z. B. Ziele für Backups und Spiegelungen, von geringer Priorität.


