---
permalink: health-checker/task_edit_individual_aggregate_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, aggregate, health, threshold, settings 
summary: Sie können die Statusschwellenwerte für Aggregatskapazität, Wachstum und Snapshot Kopien eines oder mehrerer Aggregate bearbeiten. Wenn ein Schwellenwert überschritten wird, werden Warnungen erzeugt und Sie erhalten Benachrichtigungen. Diese Benachrichtigungen helfen Ihnen, auf Basis des generierten Ereignisses vorbeugende Maßnahmen zu ergreifen. 
---
= Bearbeiten einzelner Zustandsschwellenwerte für das Aggregat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Statusschwellenwerte für Aggregatskapazität, Wachstum und Snapshot Kopien eines oder mehrerer Aggregate bearbeiten. Wenn ein Schwellenwert überschritten wird, werden Warnungen erzeugt und Sie erhalten Benachrichtigungen. Diese Benachrichtigungen helfen Ihnen, auf Basis des generierten Ereignisses vorbeugende Maßnahmen zu ergreifen.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Basierend auf Änderungen an den Schwellenwerten werden Ereignisse im nächsten Überwachungszyklus generiert oder veraltet.

Wenn Autogrow auf Volumes im Aggregat aktiviert ist, gilt die Kapazitätsschwellenwerte für die Aggregat basierend auf der durch Autogrow festgelegten maximalen Volume-Größe, nicht jedoch auf der ursprünglichen Volume-Größe.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Storage* > *Aggregate*.
. Wählen Sie in der Ansicht *Health: Alle Aggregate* einen oder mehrere Aggregate aus und klicken Sie dann auf *Schwellenwerte bearbeiten*.
. Bearbeiten Sie im Dialogfeld *Aggregat Schwellenwerte bearbeiten* die Schwellenwerteinstellungen eines der folgenden Optionen: Kapazität, Wachstum oder Snapshot Kopien, indem Sie das entsprechende Kontrollkästchen aktivieren und dann die Einstellungen ändern.
. Klicken Sie Auf *Speichern*.


*Verwandte Informationen*

link:../config/task_add_users.html["Benutzer hinzufügen"]
