---
permalink: health-checker/task_view_how_user_authentication_is_being_managed_on_all_clusters.html 
sidebar: sidebar 
keywords: view, cluster authentication status, user authentication, manage, clusters 
summary: Auf der Seite Sicherheit werden die Authentifizierungstypen angezeigt, die zur Authentifizierung von Benutzern in jedem Cluster verwendet werden, sowie die Anzahl der Benutzer, die mit jedem Typ auf das Cluster zugreifen. So können Sie überprüfen, ob die Benutzerauthentifizierung gemäß den Anforderungen Ihres Unternehmens sicher durchgeführt wird. 
---
= Anzeige des Managements der Benutzerauthentifizierung auf allen Clustern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Sicherheit werden die Authentifizierungstypen angezeigt, die zur Authentifizierung von Benutzern in jedem Cluster verwendet werden, sowie die Anzahl der Benutzer, die mit jedem Typ auf das Cluster zugreifen. So können Sie überprüfen, ob die Benutzerauthentifizierung gemäß den Anforderungen Ihres Unternehmens sicher durchgeführt wird.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Dashboard*.
. Wählen Sie oben im Dashboard im Dropdown-Menü * Alle Cluster* aus.
. Klicken Sie im Fenster *Sicherheit* auf den rechten Pfeil, und die Seite *Sicherheit* wird angezeigt.
. Zeigen Sie die *Cluster Authentication*-Karte an, um die Anzahl der Benutzer anzuzeigen, die mit jedem Authentifizierungstyp auf das System zugreifen.
. Zeigen Sie die *Cluster Security*-Karte an, um die Authentifizierungsmechanismen anzuzeigen, die zur Authentifizierung von Benutzern in jedem Cluster verwendet werden.


Wenn einige Benutzer über eine unsichere Methode auf das System zugreifen oder eine Methode verwenden, die von NetApp nicht empfohlen wird, können Sie die Methode deaktivieren.
