---
permalink: health-checker/task_edit_group_rules.html 
sidebar: sidebar 
keywords: edit, group rules 
summary: Sie können Gruppenregeln bearbeiten, um die Bedingungsgruppen und die Bedingungen innerhalb einer Bedingungsgruppe zu ändern, um Speicherobjekte zu oder aus einer bestimmten Gruppe hinzuzufügen oder zu entfernen. 
---
= Gruppenregeln werden bearbeitet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Gruppenregeln bearbeiten, um die Bedingungsgruppen und die Bedingungen innerhalb einer Bedingungsgruppe zu ändern, um Speicherobjekte zu oder aus einer bestimmten Gruppe hinzuzufügen oder zu entfernen.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Gruppen*.
. Wählen Sie auf der Registerkarte *Gruppenregeln* die Gruppenregel aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie im Dialogfeld *Gruppenregel bearbeiten* den Namen der Gruppenregel, den zugeordneten Gruppennamen, die Bedingungsgruppen und die Bedingungen, falls erforderlich.
+
[NOTE]
====
Sie können den Zielobjekttyp für eine Gruppenregel nicht ändern.

====
. Klicken Sie Auf *Speichern*.

