---
permalink: health-checker/task_edit_group_actions.html 
sidebar: sidebar 
keywords: edit, group actions 
summary: Sie können die Aktionsparameter der Gruppe bearbeiten, die Sie in Unified Manager konfiguriert haben, z. B. den Gruppenactionnamen, die Beschreibung, den zugeordneten Gruppennamen und die Parameter des Aktionstyps. 
---
= Gruppenaktionen werden bearbeitet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Aktionsparameter der Gruppe bearbeiten, die Sie in Unified Manager konfiguriert haben, z. B. den Gruppenactionnamen, die Beschreibung, den zugeordneten Gruppennamen und die Parameter des Aktionstyps.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Gruppen*.
. Wählen Sie auf der Registerkarte *Gruppenaktionen* die Gruppenaktion aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Bearbeiten*.
. Ändern Sie im Dialogfeld *Gruppenaktion* den Gruppenaktionnamen, die Beschreibung, den zugeordneten Gruppennamen und die Parameter des Aktionstyps nach Bedarf.
. Klicken Sie Auf *Speichern*.

