---
permalink: health-checker/task_delete_group_actions.html 
sidebar: sidebar 
keywords: delete, group actions 
summary: Sie können eine Gruppenaktion aus Unified Manager löschen, wenn die Gruppenaktion nicht mehr erforderlich ist. 
---
= Gruppenaktionen werden gelöscht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Gruppenaktion aus Unified Manager löschen, wenn die Gruppenaktion nicht mehr erforderlich ist.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Wenn Sie die Gruppenaktion für den Schwellenwert für den Systemzustand des Volumes löschen, werden globale Schwellenwerte auf die Speicherobjekte in dieser Gruppe angewendet. Zustandsschwellenwerte auf Objektebene, die für das Storage-Objekt festgelegt sind, werden nicht beeinträchtigt.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherverwaltung* > *Gruppen*.
. Wählen Sie auf der Registerkarte *Gruppenaktionen* die Gruppenaktion aus, die Sie löschen möchten, und klicken Sie dann auf *Löschen*.
. Bestätigen Sie im Dialogfeld *Warnung* den Löschvorgang, indem Sie auf *Ja* klicken.

