---
permalink: health-checker/task_view_detailed_security_status_for_clusters_and_svms.html 
sidebar: sidebar 
keywords: view, cluster security status, svm security status, volume encryption status 
summary: Die Seite Sicherheit zeigt den allgemeinen Sicherheitsstatus aller Cluster sowie einen detaillierten Sicherheitsstatus für einzelne Cluster an. Der detaillierte Cluster-Status umfasst Cluster-Compliance, SVM-Compliance und Volume-Verschlüsselung. 
---
= Anzeigen des detaillierten Sicherheitsstatus für Cluster und Storage-VMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite Sicherheit zeigt den allgemeinen Sicherheitsstatus aller Cluster sowie einen detaillierten Sicherheitsstatus für einzelne Cluster an.

Als Systemadministrator können Sie die Seite *Sicherheit* verwenden, um einen Überblick über die Sicherheitsstärke Ihrer ONTAP Cluster und Storage VMs auf Datacenter- und Standortebene zu erhalten.

Auf Basis der definierten Parameter können Sie Informationen erfassen und analysieren, um verdächtige Verhaltensweisen oder nicht autorisierte Systemänderungen auf den überwachten Clustern und Storage-VMs zu erkennen.

Der detaillierte Cluster-Status umfasst Cluster-Compliance, SVM-Compliance und Volume-Verschlüsselung.

Die Seite Cluster / Security Details bietet eine Standardansicht der Sicherheitskonformität der Cluster durch Überprüfen der Sicherheitsparameter wie Global FIPS, Telnet, unsichere SSH-Einstellungen, Anmeldebanner, Netzwerkzeitprotokoll, AutoSupport HTTPS-Übertragung und Standard-Admins.

Die Seite Storage VMs/ Security Details bietet eine Standardansicht der Sicherheitskonformität der Storage-VMs, indem die Sicherheitsparameter wie Storage-VMs, Cluster, Anmeldebanner, Revisionsprotokoll und unsichere SSH-Einstellungen überprüft werden.

Sie können auch auf den Detailseiten für Cluster- und Storage-VMs Berichte zu Sicherheits-Compliance erstellen, planen und herunterladen.

Klicken Sie im *Security Dashboard* auf *Berichte anzeigen* auf den Karten *Cluster Compliance* und *Storage VMs Compliance*.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Dashboard*.
. Je nachdem, ob Sie den Sicherheitsstatus für alle überwachten Cluster oder für einen einzelnen Cluster anzeigen möchten, wählen Sie *Alle Cluster* oder wählen Sie einen einzelnen Cluster aus dem Dropdown-Menü aus.
. Klicken Sie im Fenster *Sicherheit* auf den Rechtspfeil.
+
Auf der Seite Sicherheit werden die folgenden Informationen angezeigt:

+
** Cluster-Sicherheitsstatus (Anzahl an kompatiblen oder nicht kompatiblen Clustern)
** Der SVM-Sicherheitsstatus (Anzahl an konformen oder nicht konformen SVMs)
** Status der Volume-Verschlüsselung (Anzahl der verschlüsselten oder nicht verschlüsselten Volumes)
** Die Cluster-Authentifizierungsmethoden, die in den einzelnen Clustern verwendet werden


. Eine Anleitung, wie Sie alle Ihre Cluster, SVMs und Volumes mit den NetApp Sicherheitsempfehlungen konform gestalten, finden Sie im https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["NetApp Leitfaden zur verstärkte Sicherheit in ONTAP 9"^] .

