---
permalink: health-checker/task_add_annotations_dynamically.html 
sidebar: sidebar 
keywords: add, annotations, dynamically 
summary: 'Beim Erstellen benutzerdefinierter Annotationen ordnet Unified Manager Cluster, Storage Virtual Machines (SVMs) und Volumes anhand von Regeln dynamisch den Annotationen zu. Diese Regeln weisen die Anmerkungen automatisch den Speicherobjekten zu.' 
---
= Anmerkungen werden dynamisch hinzugefügt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beim Erstellen benutzerdefinierter Annotationen ordnet Unified Manager Cluster, Storage Virtual Machines (SVMs) und Volumes anhand von Regeln dynamisch den Annotationen zu. Diese Regeln weisen die Anmerkungen automatisch den Speicherobjekten zu.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Storage-Management* > *Anmerkungen*.
. Klicken Sie auf der Seite *Anmerkungen* auf *Anmerkung hinzufügen*.
. Geben Sie im Dialogfeld *Anmerkung hinzufügen* einen Namen und eine Beschreibung für die Anmerkung ein.
. Optional: Klicken Sie im Abschnitt *Anmerkungswerte* auf *Hinzufügen*, um der Anmerkung Werte hinzuzufügen.
. Klicken Sie Auf *Speichern*.

