---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, linux, snapshot, backup, windows, copy, copies 
summary: Im Falle eines Datenverlustes oder einer Beschädigung von Daten können Sie Unified Manager in den vorherigen stabilen Zustand bei minimalem Datenverlust wiederherstellen. Sie können die Snapshot-Datenbank von Unified Manager mithilfe der Wartungskonsole auf einem lokalen oder Remote-Betriebssystem wiederherstellen. 
---
= Wiederherstellung von Unified Manager mit Snapshot Kopien für Linux und Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Falle eines Datenverlustes oder einer Beschädigung von Daten können Sie Unified Manager in den vorherigen stabilen Zustand bei minimalem Datenverlust wiederherstellen. Sie können die Snapshot-Datenbank von Unified Manager mithilfe der Wartungskonsole auf einem lokalen oder Remote-Betriebssystem wiederherstellen.

*Was Sie brauchen*

* Sie müssen über die Stammbenutzeranmeldeinformationen für den Linux-Host und die Administratorrechte für Windows-Hostcomputer verfügen, auf dem Unified Manager installiert ist.
* Sie müssen über eine Benutzer-ID und ein Passwort verfügen, um sich bei der Wartungskonsole des Unified Manager-Servers anzumelden.


Die Wiederherstellungsfunktion ist plattformspezifisch und versionsspezifisch. Sie können ein Unified Manager-Backup nur auf derselben Version von Unified Manager wiederherstellen.

.Schritte
. Stellen Sie eine Verbindung mit der IP-Adresse oder dem vollqualifizierten Domänennamen des Unified Manager Systems her.
+
** Linux: Sichere Shell
** Windows: Power Shell


. Melden Sie sich mit den Anmeldedaten des Root-Benutzers beim System an.
. Geben Sie den Befehl ein `maintenance_console` Und drücken Sie die Eingabetaste.
. Geben Sie in der Wartungskonsole *Hauptmenü* 4 für die Option *Sicherungswiederherstellung* ein.
. Geben Sie 2 ein, um *Backup und Restore mit NetApp Snapshot* auszuwählen.
+
Wenn Sie eine Wiederherstellung auf einem neuen Server durchführen, starten Sie nach der Installation von Unified Manager die UI nicht oder konfigurieren Sie nach Abschluss der Installation keine Cluster, Benutzer oder Authentifizierungseinstellungen. Geben Sie 1 ein, um *NetApp Snapshot Backup konfigurieren* auszuwählen und die Einstellungen für Snapshot Kopien so zu konfigurieren, wie sie sich auf dem Originalsystem befinden.

. Geben Sie 3 ein, um *Restore mit NetApp Snapshot* auszuwählen.
. Wählen Sie die Snapshot Kopie aus, aus der Sie Unified Manager wiederherstellen möchten. Drücken Sie *Enter*.
. Melden Sie sich nach Abschluss des Wiederherstellungsprozesses in der Benutzeroberfläche von Unified Manager an.


Wenn der Workflow Automation-Server nach der Wiederherstellung des Backups nicht funktioniert, führen Sie die folgenden Schritte aus:

. Ändern Sie auf dem Workflow Automation Server die IP-Adresse des Unified Manager-Servers, um auf die neueste Maschine zu verweisen.
. Setzen Sie auf dem Unified Manager-Server das Datenbankkennwort zurück, wenn die Erfassung in Schritt 1 fehlschlägt.

