---
permalink: health-checker/task_specify_destination_location_for_windows_snapshot_backups.html 
sidebar: sidebar 
keywords: specify, destination location, windows, snapshot, backups, copy, copies 
summary: Sie sollten den Zielspeicherort für Active IQ Unified Manager Snapshot Kopien auf einem Volume konfigurieren, das Sie bereits in einem der ONTAP Cluster konfiguriert haben. Sie sollten die Wartungskonsole verwenden, um die Position zu definieren. 
---
= Festlegen des Zielorts für Snapshot Kopien unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten den Zielspeicherort für Active IQ Unified Manager Snapshot Kopien auf einem Volume konfigurieren, das Sie bereits in einem der ONTAP Cluster konfiguriert haben. Sie sollten die Wartungskonsole verwenden, um die Position zu definieren.

* Sie müssen über die Administratorberechtigung für Windows Host verfügen, auf dem Active IQ Unified Manager installiert ist.
* Sie müssen über eine Benutzer-ID und ein Passwort verfügen, um sich bei der Wartungskonsole des Unified Manager-Servers anzumelden.
* Sie müssen über die IP-Adresse für das Cluster-Management, den Namen der Storage-VM, den Namen des Volumes, den LUN-Namen und den Benutzernamen und das Kennwort des Speichersystems verfügen.
* Sie müssen das Volume als Netzwerklaufwerk auf den Active IQ Unified Manager-Host gemountet haben, und Sie müssen das Mount-Laufwerk haben.


.Schritte
. Stellen Sie mithilfe von Power Shell eine Verbindung mit der IP-Adresse oder dem vollständig qualifizierten Domänennamen des Active IQ Unified Manager-Systems her.
. Melden Sie sich beim System mit dem Wartungs-Benutzer (umadmin) und dem Passwort an.
. Geben Sie den Befehl ein `maintenance_console` Und drücken Sie die Eingabetaste.
. Geben Sie in der Wartungskonsole *Hauptmenü* die Nummer für die Option *Backup Restore* ein.
. Geben Sie die Nummer für * NetApp Snapshot Backup konfigurieren* ein.
. Geben Sie die Nummer ein, die iSCSI konfiguriert werden soll.
. Überprüfen Sie die Informationen, die Sie angeben müssen, und geben Sie dann die Nummer für *Backup Configuration Details* ein.
. Um das Volume zu identifizieren, auf dem der Snapshot geschrieben werden soll, geben Sie die IP-Adresse der Cluster Management-Schnittstelle, den Namen der Storage-VM, den Namen des Volumes, den LUN-Namen, den Benutzernamen und das Kennwort des Storage-Systems und das Mount-Laufwerk ein.
. Überprüfen Sie diese Informationen, und geben Sie ein `y`.
+
Das System führt die folgenden Aufgaben aus:

+
** Storage VM ist validiert
** Volume wird validiert
** Mount-Laufwerk und Status werden validiert
** Die LUN ist vorhanden und ihr Status ist
** Netzwerklaufwerk vorhanden
** Die Existenz des empfohlenen Speicherplatzes (mehr als doppelt so viele mysql-Datenverzeichnisses) auf gemounttem Volume wird validiert
** LUN-Pfad, der der dedizierten LUN in dem Volume entspricht
** der initiatorgruppenname
** GUID des Volumes, auf dem das Netzwerklaufwerk angehängt ist
** ISCSI Initiator zur Kommunikation mit ONTAP


. Beenden Sie die Wartungskonsole und starten Sie die Schnittstelle Active IQ Unified Manager, um einen Zeitplan für die Snapshot Kopien zu erstellen.

