---
permalink: health-checker/task_retrieve_support_bundle_using_unix_or_linux_client.html 
sidebar: sidebar 
keywords: retrieve, support bundle, unix, linux, client 
summary: 'Wenn Sie UNIX- oder Linux-Benutzer sind, können Sie das Support Bundle über Ihre vApp abrufen, indem Sie die Befehlszeilenschnittstelle (CLI) auf Ihrem Linux-Client-Server verwenden. Sie können das Supportpaket entweder mit SCP oder SFTP abrufen.' 
---
= Abrufen des Support-Pakets über einen UNIX oder Linux Client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie UNIX- oder Linux-Benutzer sind, können Sie das Support Bundle über Ihre vApp abrufen, indem Sie die Befehlszeilenschnittstelle (CLI) auf Ihrem Linux-Client-Server verwenden. Sie können das Supportpaket entweder mit SCP oder SFTP abrufen.

*Was Sie brauchen*

Sie müssen der Wartungbenutzer sein, um diese Aufgabe ausführen zu können.

Sie müssen ein Support-Bundle mit der Wartungskonsole generiert haben und den Support-Bundle-Namen haben.

.Schritte
. Greifen Sie über Telnet oder die Konsole auf die CLI über Ihren Linux-Client-Server zu.
. Auf das zugreifen /`support` Verzeichnis.
. Rufen Sie das Support Bundle ab und kopieren Sie es mit dem folgenden Befehl in das lokale Verzeichnis:
+
[cols="2*"]
|===
| Sie verwenden... | Verwenden Sie dann den folgenden Befehl... 


 a| 
SCP
 a| 
`scp <maintenance-user>@<vApp-name-or-ip>:/support/support_bundle_file_name.7z <destination-directory>`



 a| 
SFTP
 a| 
`sftp <maintenance-user>@<vApp-name-or-ip>:/support/support_bundle_file_name.7z <destination-directory>`

|===
+
Der Name des Support-Pakets wird Ihnen bereitgestellt, wenn Sie es mit der Wartungskonsole erstellen.

. Geben Sie das Wartungs-Benutzerpasswort ein.




== Beispiele

Im folgenden Beispiel wird SCP verwendet, um das Supportpaket abzurufen:

[listing]
----

        `$ scp admin@10.10.12.69:/support/support_bundle_20160216_145359.7z .`
Password: `<maintenance_user_password>`
support_bundle_20160216_145359.7z   100%  119MB  11.9MB/s   00:10
----
Im folgenden Beispiel wird SFTP zum Abrufen des Supportpakets verwendet:

[listing]
----

        `$ sftp admin@10.10.12.69:/support/support_bundle_20160216_145359.7z .`
Password: `<maintenance_user_password>`
Connected to 10.228.212.69.
Fetching /support/support_bundle_20130216_145359.7z to ./support_bundle_20130216_145359.7z
/support/support_bundle_20160216_145359.7z
----