---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: Sie können das Instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde. Sie können das Passwort optional zurücksetzen, falls Ihr Standort diese Sicherheitsfunktion erfordert, um die Installationseinstellung für Unified Manager zu überschreiben. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde. Sie können das Passwort optional zurücksetzen, falls Ihr Standort diese Sicherheitsfunktion erfordert, um die Installationseinstellung für Unified Manager zu überschreiben. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet.

*Was Sie brauchen*

* Sie sollten Windows-Administratorrechte für das System besitzen, auf dem Unified Manager installiert ist.
* Sie sollten das Passwort für den MySQL-Root-Benutzer haben.
* Sie sollten auf die von NetApp bereitgestellte Lösung zugreifen können `password.bat` Skript im Verzeichnis
+
`\Program Files\NetApp\essentials\bin`.



.Schritte
. Melden Sie sich als Admin-Benutzer auf der Unified Manager-Host-Maschine an.
. Beenden Sie mithilfe der Windows Services-Konsole die folgenden Unified Manager-Services:
+
** Erwerbsservice für NetApp Active IQ (Ozie-au)
** NetApp Active IQ Management Server-Service (OnCommandsvc)


. Starten Sie den `password.bat` Skript zum Starten des Passwortänderungsprozesses:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Geben Sie bei entsprechender Aufforderung das Passwort für den Benutzer MySQL Root ein.
. Geben Sie bei Aufforderung das neue JBoss-Benutzerpasswort ein, und geben Sie es zur Bestätigung erneut ein.
+
Beachten Sie, dass das Passwort zwischen 8 und 16 Zeichen lang sein muss und mindestens eine Ziffer, ein Großbuchstaben und ein Kleinbuchstaben sowie mindestens eines der folgenden Sonderzeichen enthalten muss:

+
`+!@%^*-_+=[]:<>.?/~+`

. Starten Sie nach Abschluss des Skripts die Unified Manager-Dienste über die Windows-Dienstkonsole:
+
** NetApp Active IQ Management Server-Service (OnCommandsvc)
** Erwerbsservice für NetApp Active IQ (Ozie-au)


. Nachdem alle Services gestartet wurden, können Sie sich in der UI von Unified Manager einloggen.

