---
permalink: config/concept_manage_feature_settings.html 
sidebar: sidebar 
keywords: uploading scripts, api gateway, slo or policy-based storage management, timeout, active iq platform events 
summary: Auf der Seite „Funktionseinstellungen“ können Sie bestimmte Funktionen in Active IQ Unified Manager aktivieren und deaktivieren. Dazu gehört auch die Erstellung und Verwaltung von Speicherobjekten auf Basis von Richtlinien, Aktivierung des API-Gateways, Hochladen von Skripten zur Verwaltung von Warnmeldungen, das Timing einer Web-UI-Sitzung basierend auf der Inaktivitätszeit und das Deaktivieren des Eingangs von Active IQ-Plattformereignissen. 
---
= Funktionseinstellungen verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Funktionseinstellungen“ können Sie bestimmte Funktionen in Active IQ Unified Manager aktivieren und deaktivieren. Dazu gehört auch die Erstellung und Verwaltung von Speicherobjekten auf Basis von Richtlinien, die Aktivierung von API-Gateway und Anmelde-Banner, das Hochladen von Skripten zur Verwaltung von Warnmeldungen, das Timing einer Web-UI-Sitzung nach Inaktivität und das Deaktivieren des Empfangs von Active IQ Plattform-Ereignissen.

[NOTE]
====
Die Seite Funktionseinstellungen ist nur für Benutzer mit Anwendungsadministratorrolle verfügbar.

====
Informationen zum Hochladen von Skripts finden Sie unter link:task_enable_and_disable_ability_to_upload_scripts.html["Aktivieren und Deaktivieren des Hochladen von Skripten"].
