---
permalink: config/reference_identity_provider_requirements_um.html 
sidebar: sidebar 
keywords: identity, provider, requirements 
summary: 'Wenn Sie Unified Manager für die Verwendung eines Identitäts-Providers (IdP) konfigurieren, um die SAML-Authentifizierung für alle Remote-Benutzer durchzuführen, müssen Sie einige erforderliche Konfigurationseinstellungen beachten, damit die Verbindung zu Unified Manager erfolgreich hergestellt wird.' 
---
= Anforderungen an Identitätsanbieter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Unified Manager für die Verwendung eines Identitäts-Providers (IdP) konfigurieren, um die SAML-Authentifizierung für alle Remote-Benutzer durchzuführen, müssen Sie einige erforderliche Konfigurationseinstellungen beachten, damit die Verbindung zu Unified Manager erfolgreich hergestellt wird.

Sie müssen die Unified Manager-URI und die Metadaten im IdP-Server eingeben. Sie können diese Informationen von der Seite Unified ManagerSAML Authentication kopieren. Unified Manager gilt im SAML-Standard (Security Assertion Markup Language) als Service Provider (SP).



== Unterstützte Verschlüsselungsstandards

* Advanced Encryption Standard (AES): AES-128 und AES-256
* Sicherer Hash-Algorithmus (SHA): SHA-1 und SHA-256




== Validierte Identitätsanbieter

* Shibboleth
* Active Directory Federation Services (ADFS)




== ADFS-Konfigurationsanforderungen

* Sie müssen drei Antragsregeln in der folgenden Reihenfolge definieren, die erforderlich sind, damit Unified Manager ADFS SAML-Antworten für diesen Vertrauenseintrag der Treuhandgesellschaft analysieren kann.
+
[cols="2*"]
|===
| Forderungsregel | Wert 


 a| 
SAM-Account-Name
 a| 
Name-ID



 a| 
SAM-Account-Name
 a| 
Urne:oid:0.9.2342.19200300.100.1.1



 a| 
Token-Gruppen -- Unqualifizierter Name
 a| 
Urne:oid:1.3.6.1.4.1.5923.1.5.1.1

|===
* Sie müssen die Authentifizierungsmethode auf „`Forms Authentication`“ setzen, oder Benutzer erhalten möglicherweise einen Fehler beim Abmelden von Unified Manager. Führen Sie hierzu folgende Schritte aus:
+
.. Öffnen Sie die ADFS-Verwaltungskonsole.
.. Klicken Sie in der linken Strukturansicht auf den Ordner Authentication Policies.
.. Klicken Sie unter Aktionen auf der rechten Seite auf Globale primäre Authentifizierungsrichtlinie bearbeiten.
.. Setzen Sie die Intranet-Authentifizierungsmethode auf „`Forms Authentication`“ anstatt auf die Standardauthentifizierung „`Windows Authentication`“.


* In einigen Fällen wird die Anmeldung über das IdP abgelehnt, wenn das Unified Manager-Sicherheitszertifikat CA-signiert ist. Es gibt zwei Problemumgehungen zur Lösung dieses Problems:
+
** Befolgen Sie die Anweisungen im Link, um die Widerrufs-Prüfung auf dem ADFS-Server für verkettete CA-Zertifikat zugeordnete abhängige Partei zu deaktivieren:
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/["Deaktivieren Sie die Überprüfung der Widerruferstellung pro Vertrauen der Vertrauensgruppe"]

** Der CA-Server befindet sich im ADFS-Server, um die Zertifiktanforderung des Unified Manager-Servers zu signieren.






== Sonstige Konfigurationsanforderungen

* Die Unified Manager-Taktskew ist auf 5 Minuten eingestellt, sodass der Zeitunterschied zwischen dem IdP-Server und dem Unified Manager-Server nicht mehr als 5 Minuten betragen kann oder die Authentifizierung fehlschlägt.

