---
permalink: config/task_change_umadmin_password_on_rhel.html 
sidebar: sidebar 
keywords: change, umadmin, password, linux systems 
summary: Aus Sicherheitsgründen müssen Sie das Standardpasswort für den Unified Manager umadmin-Benutzer sofort nach Abschluss des Installationsprozesses ändern. Sie können das Passwort bei Bedarf jederzeit später wieder ändern. 
---
= Ändern des umadmin-Passworts auf Linux-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aus Sicherheitsgründen müssen Sie das Standardpasswort für den Unified Manager umadmin-Benutzer sofort nach Abschluss des Installationsprozesses ändern. Sie können das Passwort bei Bedarf jederzeit später wieder ändern.

*Was Sie brauchen*

* Unified Manager muss auf einem Red hat Enterprise Linux oder CentOS Linux System installiert sein.
* Sie müssen über die Stammbenutzer-Anmeldeinformationen für das Linux-System verfügen, auf dem Unified Manager installiert ist.


.Schritte
. Melden Sie sich als Root-Benutzer an dem Linux-System an, auf dem Unified Manager ausgeführt wird.
. Ändern Sie das umadmin-Passwort:
+
`passwd umadmin`

+
Das System fordert Sie zur Eingabe eines neuen Passworts für den umadmin-Benutzer auf.


