---
permalink: config/task_change_maintenance_user_password_on_windows.html 
sidebar: sidebar 
keywords: change, maintenance, user, password, windows 
summary: Sie können bei Bedarf das Passwort des Unified Manager-Wartungsbenutzers ändern. 
---
= Ändern des Wartungsbenutzerkennworts unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können bei Bedarf das Passwort des Unified Manager-Wartungsbenutzers ändern.

.Schritte
. Klicken Sie auf der Anmeldeseite der Web-Benutzeroberfläche von Unified Manager auf *Passwort vergessen*.
+
Es wird eine Seite angezeigt, die den Namen des Benutzers auffordert, dessen Kennwort Sie zurücksetzen möchten.

. Geben Sie den Benutzernamen ein und klicken Sie auf *Absenden*.
+
Eine E-Mail mit einem Link zum Zurücksetzen des Passworts wird an die für diesen Benutzernamen definierte E-Mail-Adresse gesendet.

. Klicken Sie in der E-Mail auf den Link *Passwort zurücksetzen* und definieren Sie das neue Passwort.
. Kehren Sie zur Web-Benutzeroberfläche zurück und melden Sie sich mit dem neuen Passwort bei Unified Manager an.

