---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: Sie können Ihr lokales Benutzeranmeldeswort ändern, um potenzielle Sicherheitsrisiken zu vermeiden. 
---
= Ändern des lokalen Benutzerpassworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihr lokales Benutzeranmeldeswort ändern, um potenzielle Sicherheitsrisiken zu vermeiden.

*Was Sie brauchen*

Sie müssen als lokaler Benutzer angemeldet sein.

Die Passwörter für den Wartungsbenutzer und für Remote-Benutzer können mit diesen Schritten nicht geändert werden. Wenden Sie sich an Ihren Passwortadministrator, um ein Kennwort für Remote-Benutzer zu ändern. Informationen zum Ändern des Wartungs-Benutzerpassworts finden Sie unter link:task_use_maintenance_console.html["Verwenden der Wartungskonsole"].

.Schritte
. Melden Sie sich bei Unified Manager an.
. Klicken Sie in der oberen Menüleiste auf das Benutzersymbol und dann auf *Passwort ändern*.
+
Die Option *Passwort ändern* wird nicht angezeigt, wenn Sie ein Remote-Benutzer sind.

. Geben Sie im Dialogfeld Passwort ändern das aktuelle Passwort und das neue Passwort ein.
. Klicken Sie Auf *Speichern*.


Wenn Unified Manager in einer Hochverfügbarkeitskonfiguration konfiguriert ist, müssen Sie das Passwort auf dem zweiten Node des Setup ändern. Beide Instanzen müssen dasselbe Passwort haben.
