---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: Sie können die Konfiguration Ihrer Authentifizierungsserver überprüfen, um sicherzustellen, dass der Verwaltungsserver mit diesen Servern kommunizieren kann. Sie können die Konfiguration validieren, indem Sie von Ihren Authentifizierungsservern nach einem Remote-Benutzer oder einer Remotegruppe suchen und diese unter Verwendung der konfigurierten Einstellungen authentifizieren. 
---
= Die Konfiguration der Authentifizierungsserver wird getestet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Konfiguration Ihrer Authentifizierungsserver überprüfen, um sicherzustellen, dass der Verwaltungsserver mit diesen Servern kommunizieren kann. Sie können die Konfiguration validieren, indem Sie von Ihren Authentifizierungsservern nach einem Remote-Benutzer oder einer Remotegruppe suchen und diese unter Verwendung der konfigurierten Einstellungen authentifizieren.

*Was Sie brauchen*

* Sie müssen die Remote-Authentifizierung aktiviert und Ihren Authentifizierungsdienst so konfiguriert haben, dass der Unified Manager-Server den Remote-Benutzer oder die Remote-Gruppe authentifizieren kann.
* Sie müssen Ihre Authentifizierungsserver hinzugefügt haben, damit der Verwaltungsserver von diesen Servern nach dem Remote-Benutzer oder der Remote-Gruppe suchen und diese authentifizieren kann.
* Sie müssen über die Anwendungsadministratorrolle verfügen.


Wenn der Authentifizierungsservice auf Active Directory festgelegt ist und Sie die Authentifizierung von Remote-Benutzern validieren, die zur primären Gruppe des Authentifizierungsservers gehören, werden in den Authentifizierungsergebnissen keine Informationen zur primären Gruppe angezeigt.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *Remote Authentication*.
. Klicken Sie Auf *Authentifizierung Testen*.
. Geben Sie im Dialogfeld Testbenutzer den Benutzernamen und das Kennwort des Remote-Benutzers oder des Benutzernamens der Remote-Gruppe ein, und klicken Sie dann auf *Test*.
+
Wenn Sie eine Remote-Gruppe authentifizieren, müssen Sie das Kennwort nicht eingeben.


