---
permalink: config/task_disable_nested_groups_from_remote_authentication.html 
sidebar: sidebar 
keywords: disable, nested groups, remote, authentication 
summary: Wenn die Remote-Authentifizierung aktiviert ist, können Sie die verschachtelte Gruppenauthentifizierung deaktivieren, sodass sich nur einzelne Benutzer und nicht Gruppenmitglieder im Remote-Zugriff auf Unified Manager authentifizieren können. Sie können verschachtelte Gruppen deaktivieren, wenn Sie die Reaktionszeit der Active Directory-Authentifizierung verbessern möchten. 
---
= Deaktivieren verschachtelter Gruppen von der Remote-Authentifizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die Remote-Authentifizierung aktiviert ist, können Sie die verschachtelte Gruppenauthentifizierung deaktivieren, sodass sich nur einzelne Benutzer und nicht Gruppenmitglieder im Remote-Zugriff auf Unified Manager authentifizieren können. Sie können verschachtelte Gruppen deaktivieren, wenn Sie die Reaktionszeit der Active Directory-Authentifizierung verbessern möchten.

*Was Sie brauchen*

* Sie müssen über die Anwendungsadministratorrolle verfügen.
* Das Deaktivieren verschachtelter Gruppen ist nur bei Verwendung von Active Directory anwendbar.


Wenn Sie die Unterstützung für verschachtelte Gruppen in Unified Manager deaktivieren, wird die Authentifizierungszeit möglicherweise verkürzt. Wenn die Unterstützung verschachtelter Gruppen deaktiviert ist und eine Remote-Gruppe zu Unified Manager hinzugefügt wird, müssen einzelne Benutzer Mitglieder der Remote-Gruppe sein, um sich bei Unified Manager zu authentifizieren.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *Remote Authentication*.
. Aktivieren Sie das Kontrollkästchen für *Suche nach verschachtelter Gruppe deaktivieren*.
. Klicken Sie Auf *Speichern*.

