---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: 'Sie müssen Unified Manager herunterladen `.zip` Datei von der NetApp Support Site zur Installation von Unified Manager.' 
---
= Download Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Unified Manager herunterladen `.zip` Datei von der NetApp Support Site zur Installation von Unified Manager.

*Was Sie brauchen*

Sie müssen Anmeldedaten für die NetApp Support-Website besitzen.

Sowohl für Red hat Enterprise Linux als auch für CentOS Systeme laden Sie das gleiche Unified Manager Installationspaket herunter.

.Schritte
. Loggen Sie sich auf der NetApp Support Site ein und navigieren Sie zur Download-Seite für Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp Support Website"]

. Wählen Sie die erforderliche Version von Unified Manager aus, und akzeptieren Sie die Endbenutzer-Lizenzvereinbarung (Endbenutzer License Agreement, EULA).
. Laden Sie die Installationsdatei für Unified Manager für Linux herunter, und speichern Sie die `.zip` Datei in ein Verzeichnis auf dem Zielsystem.
+
[NOTE]
====
Stellen Sie sicher, dass Sie die korrekte Version der Installationsdatei für Ihr Red hat Enterprise Linux-System herunterladen. Stellen Sie sicher, dass Sie die entsprechende Version von Unified Manager herunterladen, je nachdem, ob Red hat Enterprise Linux 7 oder 8 installiert ist `.zip` Datei:

====
. Überprüfen Sie die Prüfsumme, um sicherzustellen, dass die Software ordnungsgemäß heruntergeladen wurde.

