---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: Sie können das Instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde. Sie können das Passwort optional zurücksetzen, falls Ihr Standort diese Sicherheitsfunktion erfordert, um die Installationseinstellung für Unified Manager zu überschreiben. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Instanzspezifische JBoss-Passwort zurücksetzen, das während der Installation festgelegt wurde. Sie können das Passwort optional zurücksetzen, falls Ihr Standort diese Sicherheitsfunktion erfordert, um die Installationseinstellung für Unified Manager zu überschreiben. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet.

* Sie müssen Root-Zugriff auf das Red hat Enterprise Linux oder CentOS System haben, auf dem Unified Manager installiert ist.
* Sie müssen auf die von NetApp bereitgestellte Lösung zugreifen können `password.sh` Skript im Verzeichnis `/opt/netapp/essentials/bin`.


.Schritte
. Melden Sie sich als Root-Benutzer auf dem System an.
. Beenden Sie die Unified Manager Services, indem Sie die folgenden Befehle in der angezeigten Reihenfolge eingeben:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Beenden Sie die zugehörige MySQL-Software nicht.

. Geben Sie den folgenden Befehl ein, um den Passwortänderungsprozess zu starten:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Geben Sie bei entsprechender Aufforderung das neue JBoss-Passwort ein und bestätigen Sie es anschließend erneut.
+
Beachten Sie, dass das Passwort zwischen 8 und 16 Zeichen lang sein muss und mindestens eine Ziffer, ein Großbuchstaben und ein Kleinbuchstaben sowie mindestens eines der folgenden Sonderzeichen enthalten muss:

+
`+!@%^*-_+=[]:<>.?/~+`

. Starten Sie nach Abschluss des Skripts die Unified Manager Services, indem Sie in der angezeigten Reihenfolge die folgenden Befehle eingeben:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Nachdem alle Services gestartet wurden, können Sie sich in der UI von Unified Manager einloggen.

