---
permalink: install-linux/task_manually_configure_epel_repository.html 
sidebar: sidebar 
keywords: manually, configure, epel repository 
summary: 'Wenn das System, auf dem Sie Unified Manager installieren, keinen Zugriff auf das EPEL-Repository (Extra Packages for Enterprise Linux) hat, müssen Sie das Repository manuell herunterladen und für eine erfolgreiche Installation konfigurieren.' 
---
= Manuelles Konfigurieren des EPEL-Repositorys
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das System, auf dem Sie Unified Manager installieren, keinen Zugriff auf das EPEL-Repository (Extra Packages for Enterprise Linux) hat, müssen Sie das Repository manuell herunterladen und für eine erfolgreiche Installation konfigurieren.

Das EPEL-Repository bietet Zugriff auf die erforderlichen Drittanbieter-Dienstprogramme, die auf Ihrem System installiert werden müssen. Sie verwenden das EPEL-Repository, unabhängig davon, ob Sie Unified Manager auf einem Red hat oder CentOS-System installieren.

.Schritte
. Laden Sie das EPEL-Repository für Ihre Installation herunter. Für Red hat Enterprise Linux 7 können Sie ihn unter folgender Adresse herunterladen:
+
`+wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm+`

+
Laden Sie die Version 8 unter folgender Adresse herunter:

+
`+wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm+`

. EPEL-Repository konfigurieren:
+
`yum install epel-release-latest-<version>.noarch.rpm`



Für Red hat Enterprise Linux 8-Systeme, wenn Sie interne Repositorys mit modularen RPM-Paketen haben, zum Beispiel `_javapackages-filesystem-<version>.module.rpm_`, Sicherzustellen, dass die Metadaten für die modularen Pakete auch im selben Repository verfügbar sind.
