---
permalink: events/reference_metrocluster_switch_events.html 
sidebar: sidebar 
keywords: metrocluster, switch, events, impact area, availability 
summary: MetroCluster Switch-Ereignisse liefern Ihnen Informationen zum Status der MetroCluster Switches, damit Sie ein Monitoring auf potenzielle Probleme ermöglichen. Ereignisse sind nach Impact Area gruppiert und umfassen den Ereignis- und Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad. 
---
= Ereignisse auf dem MetroCluster-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster Switch-Ereignisse liefern Ihnen Informationen zum Status der MetroCluster Switches, damit Sie ein Monitoring auf potenzielle Probleme ermöglichen. Ereignisse sind nach Impact Area gruppiert und umfassen den Ereignis- und Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad.



== Impact Area: Verfügbarkeit

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Schalttemperatur anormal (OktEvtSwitchTemperaturAbnormal)
 a| 
Vorfall
 a| 
MetroCluster-Switch
 a| 
Kritisch



 a| 
Switch nicht erreichbar (ocumEvtSwitchnicht erreichbar)
 a| 
Vorfall
 a| 
MetroCluster-Switch
 a| 
Kritisch



 a| 
Switch-Lüfter fehlgeschlagen (ocumEvtSwitchFansOneOrMoreFailed)
 a| 
Vorfall
 a| 
MetroCluster-Switch
 a| 
Kritisch



 a| 
Switch-Netzteile fehlgeschlagen (ocumEvtSwitchPowerSuppliesOneOrMoreFailed)
 a| 
Vorfall
 a| 
MetroCluster-Switch
 a| 
Kritisch



 a| 
Schalter Temperatursensoren fehlgeschlagen (OcumEvtSwitchTemperatursensordefekt)

[NOTE]
====
Dieses Ereignis gilt nur für Cisco Switches.

==== a| 
Vorfall
 a| 
MetroCluster-Switch
 a| 
Kritisch

|===