---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, snapmirror business continuity, smbc, sm-bc 
summary: Je nach Implementierung Ihrer Topologie des Storage können Sie mit Unified Manager mehrere Arten von SnapMirror Sicherungsbeziehungen konfigurieren. Alle Varianten des SnapMirror Schutzes bieten Failover Disaster Recovery-Schutz, bieten jedoch unterschiedliche Funktionen in Bezug auf Performance, Versionsflexibilität und Sicherung mehrerer Backup-Kopien. 
---
= Arten der SnapMirror Sicherung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Je nach Implementierung Ihrer Topologie des Storage können Sie mit Unified Manager mehrere Arten von SnapMirror Sicherungsbeziehungen konfigurieren. Alle Varianten des SnapMirror Schutzes bieten Failover Disaster Recovery-Schutz, bieten jedoch unterschiedliche Funktionen in Bezug auf Performance, Versionsflexibilität und Sicherung mehrerer Backup-Kopien.



== Herkömmliche asynchrone Datensicherungsbeziehungen von SnapMirror

Herkömmlicher SnapMirror asynchroner Schutz bietet Sicherung der Blockreplizierung zwischen Quell- und Ziel-Volumes.

In herkömmlichen SnapMirror Beziehungen werden Spiegelvorgänge schneller ausgeführt als in alternativen SnapMirror Beziehungen, da der Spiegelvorgang auf der Blockreplizierung basiert. Beim herkömmlichen SnapMirror Schutz muss das Ziel-Volume jedoch unter derselben oder einer höheren kleineren Version der ONTAP Software wie das Quell-Volume innerhalb derselben größeren Version (z. B. Version 8.x zu 8.x oder 9.x zu 9.x) ausgeführt werden. Die Replizierung von einer 9.1 Quelle auf ein 9.0 Ziel wird nicht unterstützt, da auf dem Ziel eine frühere Hauptversion ausgeführt wird.



== SnapMirror Asynchronous Protection mit versionsflexibler Replizierung

SnapMirror Asynchronous Schutz mit versionsflexibler Replizierung bietet einen logischen Spiegelschutz zwischen Quell- und Ziel-Volumes, auch wenn diese Volumes unter verschiedenen Versionen von ONTAP 8.3 oder höher ausgeführt werden (z. B. Version 8.3 auf 8.3.1, 8.3 zu 9.1 oder 9.2.2 zu 9.2).

In SnapMirror Beziehungen mit versionsflexibler Replizierung werden Spiegelvorgänge nicht so schnell ausgeführt wie in herkömmlichen SnapMirror Beziehungen.

Aufgrund der langsameren Ausführung eignet sich SnapMirror mit versionsflexibler Replizierungssicherung nicht für den Einsatz unter folgenden Umständen:

* Das Quellobjekt enthält mehr als 10 Millionen Dateien, die gesichert werden müssen.
* Die Recovery-Zeitvorgabe für die geschützten Daten beträgt maximal zwei Stunden. (Das heißt, das Ziel muss immer gespiegelte, wiederherstellbare Daten enthalten, die nicht mehr als zwei Stunden älter sind als die Daten der Quelle.)


In einem der aufgeführten Situationen ist die schnellere blockbasierte Ausführung der SnapMirror Standardsicherung erforderlich.



== SnapMirror Asynchronous Protection mit versionsflexibler Replizierung und Option für Backups

SnapMirror Asynchronous Protection mit der versionsflexiblen Replizierungs- und Backup-Option bietet Spiegelschutz zwischen Quell- und Ziel-Volumes und die Möglichkeit, mehrere Kopien der gespiegelten Daten am Zielspeicherort zu speichern.

Der Storage-Administrator kann festlegen, welche Snapshot Kopien vom Quell- zum Zielsystem gespiegelt werden, und er kann auch angeben, wie lange diese Kopien am Ziel aufbewahrt werden sollen, selbst wenn sie an der Quelle gelöscht werden.

In SnapMirror Beziehungen mit versionsflexibler Replizierung und Backup-Option werden Spiegelvorgänge nicht so schnell ausgeführt wie in herkömmlichen SnapMirror Beziehungen.



== SnapMirror Unified Replication (Spiegelung und Vault)

Dank der einheitlichen Replizierung mit SnapMirror können Disaster Recovery und Archivierung auf demselben Ziel-Volume konfiguriert werden. Wie bei SnapMirror führt die einheitliche Datensicherung beim ersten Aufruf einen Basistransfer durch. Ein Basistransfer unter der standardmäßigen, einheitlichen Datenschutzrichtlinie von „`MirrorAndVault`“ erstellt eine Snapshot Kopie des Quell-Volume, dann werden diese Kopie und die Datenblöcke übertragen, auf die sie auf das Ziel-Volume verweist. Wie bei SnapVault umfasst auch die Unified Datensicherung keine älteren Snapshot Kopien in der Basiskonfiguration.



== SnapMirror synchroner Schutz mit strenger Synchronisierung

SnapMirror Synchronous Schutz mit „`strict`“-Synchronisierung sorgt dafür, dass das primäre und sekundäre Volume immer eine echte Kopie voneinander sind. Falls beim Versuch, Daten auf das sekundäre Volume zu schreiben, ein Replizierungsfehler auftritt, wird der Client-I/O auf das primäre Volume unterbrochen.



== SnapMirror synchroner Schutz mit regelmäßiger Synchronisierung

SnapMirror Synchronous Schutz mit „`regular`“-Synchronisierung erfordert nicht, dass das primäre und sekundäre Volume immer eine echte Kopie voneinander sind, wodurch die Verfügbarkeit des primären Volumes gewährleistet wird. Wenn beim Versuch, Daten auf das sekundäre Volume zu schreiben, ein Replizierungsfehler auftritt, werden die primären und sekundären Volumes nicht mehr synchronisiert und die Client-I/O-Vorgänge werden weiter zum primären Volume fortgesetzt.

[NOTE]
====
Die Schaltfläche „Wiederherstellen“ und die Schaltflächen zum Beziehungsvorgang sind nicht verfügbar, wenn synchrone Schutzbeziehungen von der Ansicht „Zustand: Alle Volumes“ oder der Seite „Volume / Health Details“ überwacht werden.

====


== SnapMirror Synchronous Business Continuity

Die SnapMirror Business Continuity Funktion (SM-BC) ist ab ONTAP 9.8 verfügbar und kann damit für die Sicherung von Applikationen mit LUNs eingesetzt werden. Auf diese Weise können Applikationen transparent ausfallen, sodass im Notfall Business Continuity gewährleistet ist.

Damit können Sie die synchronen SnapMirror Beziehungen für Konsistenzgruppen (CGS) erkennen und überwachen, die auf Clustern und Storage Virtual Machines von Unified Manager verfügbar sind. SM-BC wird auf AFF Clustern oder All SAN Array (ASA) Clustern unterstützt, bei denen die primären und sekundären Cluster entweder AFF oder ASA sein können. SM-BC sichert Applikationen mit iSCSI oder FCP LUNs.

Wenn Sie die durch die SM-BC-Beziehung geschützten Volumes und LUNs anzeigen, erhalten Sie eine einheitliche Ansicht für Sicherungsbeziehungen, Konsistenzgruppen im Volume-Bestand, Anzeigen der Schutztopologie für Consistency Group-Beziehungen, Anzeigen historischer Daten für Consistency Group-Beziehungen bis zu einem Jahr. Sie können den Bericht auch herunterladen. Sie können auch die Zusammenfassung der Konsistenzgruppenbeziehungen anzeigen, die Unterstützung von Konsistenzgruppenbeziehungen suchen und Informationen zu Volumes erhalten, die von der Konsistenzgruppe geschützt sind.

Auf der Seite „Beziehungen“ können Sie auch den Schutz der Quell- und Ziel-Storage-Objekte und ihre Beziehung, die durch die Konsistenzgruppe geschützt sind, sortieren, filtern und erweitern.

Weitere Informationen über SnapMirror Synchronous Business Continuity finden Sie unter link:https://docs.netapp.com/us-en/ontap/smbc/index.html["ONTAP 9 Dokumentation für SM-BC"].
