---
permalink: data-protection/task_create_snapvault_protection_relationship.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, health, volumes view 
summary: 'Sie können die Ansicht Systemzustand: Alle Volumes verwenden, um SnapVault-Beziehungen für ein oder mehrere Volumes auf derselben Storage-VM zu erstellen, um Daten-Backups zu Sicherungszwecken zu ermöglichen.' 
---
= Erstellen einer SnapVault-Schutzbeziehung aus der Ansicht „Systemzustand: Alle Volumes“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Ansicht Systemzustand: Alle Volumes verwenden, um SnapVault-Beziehungen für ein oder mehrere Volumes auf derselben Storage-VM zu erstellen, um Daten-Backups zu Sicherungszwecken zu ermöglichen.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.


Das Menü * Protect* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung besteht und der Ziel-Cluster noch nicht erkannt wurde


.Schritte
. Klicken Sie im linken Navigationsbereich auf *Storage* > *Volumes*.
. Wählen Sie in der Ansicht *Gesundheit: Alle Volumen* ein Volumen aus, das Sie schützen möchten, und klicken Sie auf *schützen*.
+
Wenn Sie mehrere Sicherungsbeziehungen auf derselben virtuellen Speichermaschine (SVM) erstellen möchten, wählen Sie in der Ansicht Systemzustand: Alle Volumes ein oder mehrere Volumes aus, und klicken Sie in der Symbolleiste auf *schützen*.

. Wählen Sie im Menü * SnapVault* aus.
+
Das Dialogfeld Schutz konfigurieren wird gestartet.

. Klicken Sie auf *SnapVault*, um die Registerkarte *SnapVault* anzuzeigen und die Informationen zum sekundären Volume zu konfigurieren.
. Klicken Sie auf *Erweitert*, um Deduplizierung, Komprimierung, Autogrow und Platzgarantie nach Bedarf festzulegen und klicken Sie dann auf *Apply*.
. Füllen Sie auf der Registerkarte *SnapVault* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
. Klicken Sie Auf *Anwenden*.
+
Sie werden wieder in die Ansicht „Health: All Volumes“ angezeigt.

. Klicken Sie oben in der Ansicht *Gesundheit: Alle Volumes* auf den Link für die Schutzkonfiguration.
+
Wenn Sie nur eine Schutzbeziehung erstellen, wird die Seite Jobdetails angezeigt. Wenn Sie jedoch mehr als eine Schutzbeziehung erstellen, wird eine gefilterte Liste aller Jobs angezeigt, die mit dem Schutzvorgang verknüpft sind.

. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie nur einen Job haben, klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
** Wenn Sie mehr als einen Job haben:
+
... Klicken Sie in der Liste Jobs auf einen Job.
... Klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
... Verwenden Sie die Schaltfläche *Zurück*, um zur gefilterten Liste zurückzukehren und einen anderen Job anzuzeigen.





