---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: Sie können eine SnapVault-Beziehung auf der Seite Volume / Health Details erstellen, so dass Daten-Backups für Sicherungszwecke auf Volumes aktiviert sind. 
---
= Erstellen einer SnapVault-Schutzbeziehung auf der Seite „Volume/Health Details“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SnapVault-Beziehung auf der Seite Volume / Health Details erstellen, so dass Daten-Backups für Sicherungszwecke auf Volumes aktiviert sind.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten, um diese Aufgabe auszuführen.


Das Menü * Protect* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung besteht und der Ziel-Cluster noch nicht erkannt wurde


.Schritte
. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Volumen / Gesundheit* mit der rechten Maustaste auf ein Volume in der Topologieansicht, die Sie schützen möchten.
. Wählen Sie im Menü * Protect* > *SnapVault* aus.
+
Das Dialogfeld Schutz konfigurieren wird gestartet.

. Klicken Sie auf *SnapVault*, um die Registerkarte *SnapVault* anzuzeigen und die Informationen zur sekundären Ressource zu konfigurieren.
. Klicken Sie auf *Erweitert*, um Deduplizierung, Komprimierung, Autogrow und Platzgarantie nach Bedarf festzulegen und klicken Sie dann auf *Apply*.
. Füllen Sie im Dialogfeld *Schutz konfigurieren* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
. Klicken Sie Auf *Anwenden*.
+
Sie gelangen zurück zur Seite Volume / Health Details.

. Klicken Sie oben auf der Seite *Volumen / Gesundheit* Details auf den Link für die Schutzkonfiguration.
+
Die Seite Jobdetails wird angezeigt.

. Klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
+
Wenn die Aufgabenstellungen abgeschlossen sind, werden die neuen Beziehungen auf der Topologieansicht Volume / Health Details angezeigt.


