---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: Sie können auf der Seite Volume-/Integritätsdetails eine SnapMirror Beziehung erstellen, sodass die Datenreplizierung zu Sicherungszwecken aktiviert wird. Die SnapMirror Replizierung ermöglicht Ihnen die Wiederherstellung von Daten vom Ziel-Volume im Falle eines Datenverlusts auf dem Quellsystem. 
---
= Erstellen einer SnapMirror Schutzbeziehung auf der Seite „Volume/Health Details“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf der Seite Volume-/Integritätsdetails eine SnapMirror Beziehung erstellen, sodass die Datenreplizierung zu Sicherungszwecken aktiviert wird. Die SnapMirror Replizierung ermöglicht Ihnen die Wiederherstellung von Daten vom Ziel-Volume im Falle eines Datenverlusts auf dem Quellsystem.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.


Das Menü * Protect* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung besteht und der Ziel-Cluster noch nicht erkannt wurde


Sie können bis zu 10 Sicherungsjobs gleichzeitig ausführen, ohne die Leistung zu beeinträchtigen. Möglicherweise haben Sie Auswirkungen auf die Leistung, wenn Sie zwischen 11 und 30 Jobs gleichzeitig ausführen. Es wird nicht empfohlen, mehr als 30 Jobs gleichzeitig auszuführen.

.Schritte
. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Volumen / Gesundheit* mit der rechten Maustaste in die Topologieansicht auf den Namen eines Volumes, das Sie schützen möchten.
. Wählen Sie aus dem Menü * Protect* > *SnapMirror* aus.
+
Das Dialogfeld Schutz konfigurieren wird angezeigt.

. Klicken Sie auf *SnapMirror*, um die Registerkarte *SnapMirror* anzuzeigen und die Zielinformationen zu konfigurieren.
. Klicken Sie auf *Erweitert*, um die Platzgarantie nach Bedarf festzulegen, und klicken Sie dann auf *Anwenden*.
. Füllen Sie im Dialogfeld *Schutz konfigurieren* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
. Klicken Sie Auf *Anwenden*.
+
Sie gelangen zurück zur Seite Volume / Health Details.

. Klicken Sie oben auf der Seite *Volumen / Gesundheit* Details auf den Link für die Schutzkonfiguration.
+
Die Aufgaben und Details des Jobs werden auf der Seite Jobdetails angezeigt.

. Klicken Sie auf der Seite *Job* Details auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und bestimmen Sie, wann der Job abgeschlossen ist.
. Wenn die Aufgaben abgeschlossen sind, klicken Sie auf *Zurück* in Ihrem Browser, um zur Detailseite *Volumen / Gesundheit* zurückzukehren.
+
Die neue Beziehung wird auf der Topologieansicht Volume / Health Details angezeigt.



Je nachdem, welche Ziel-SVM Sie während der Konfiguration oder in den Optionen angegeben haben, die Sie in den erweiterten Einstellungen aktiviert haben, kann die SnapMirror Beziehung eine oder mehrere mögliche Varianten sein:

* Falls Sie eine Ziel-SVM angegeben haben, die unter derselben oder einer neueren Version von ONTAP im Vergleich zur des Quell-Volume ausgeführt wird, ist eine auf Replizierung basierende SnapMirror Beziehung das Standardergebnis.
* Falls Sie eine Ziel-SVM angegeben haben, die im Vergleich zur Version des Quell-Volumes unter derselben oder einer neueren Version von ONTAP läuft, jedoch in den erweiterten Einstellungen versionsflexible Replizierung aktiviert wurde, ist das Ergebnis eine SnapMirror Beziehung mit versionsflexibler Replizierung.
* Wenn Sie eine Ziel-SVM angegeben haben, die unter einer früheren Version von ONTAP ausgeführt wird, oder eine Version, die höher ist als die des Quell-Volume, und die frühere Version unterstützt versionsflexible Replizierung. Das automatische Ergebnis ist eine SnapMirror Beziehung mit versionsflexibler Replizierung.

