---
permalink: data-protection/task_edit_protection_relationships_from_health_volume.html 
sidebar: sidebar 
keywords: edit, protection, relationships, volume, health details page 
summary: Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern. Sie können eine Beziehung bearbeiten, um die für Datentransfers verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Transfers zu erhöhen, da sich Daten oft ändern. 
---
= Bearbeiten von Schutzbeziehungen auf der Seite Volume / Health Details
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern. Sie können eine Beziehung bearbeiten, um die für Datentransfers verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Transfers zu erhöhen, da sich Daten oft ändern.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Workflow Automation muss installiert und konfiguriert sein.


Die ausgewählten Volumes müssen Schutzbeziehungsziele sein. Sie können Beziehungen nicht bearbeiten, wenn Quell-Volumes, Volumes für die Lastverteilung oder Volumes ausgewählt werden, die nicht Ziel einer SnapMirror oder SnapVault Beziehung sind.

.Schritte
. Suchen Sie auf der *Schutz*-Registerkarte der Seite *Volumen / Gesundheit* Details in der Topologie die Schutzbeziehung, die Sie bearbeiten möchten, und klicken Sie mit der rechten Maustaste darauf.
. Wählen Sie im Menü * Bearbeiten* aus.
+
Alternativ können Sie im Menü *Aktionen* die Option *Beziehung* > *Bearbeiten* wählen, um die Beziehung zu bearbeiten, für die Sie die Details anzeigen.

+
Das Dialogfeld *Beziehung bearbeiten* wird angezeigt.

. Bearbeiten Sie im Dialogfeld „Beziehung bearbeiten“ die maximale Übertragungsrate, die Schutzrichtlinie oder den Schutzzeitplan nach Bedarf.
. Klicken Sie Auf *Anwenden*.
+
Die Änderungen werden auf die ausgewählten Beziehungen angewendet.


