---
permalink: data-protection/task_break_snapmirror_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: break, snapmirror, relationship, volume, health details 
summary: Sie können eine Sicherungsbeziehung von der Seite Volume / Health Details brechen und die Datentransfers zwischen einem Quell- und Ziel-Volume in einer SnapMirror Beziehung stoppen. Wenn Sie Daten migrieren, für Disaster Recovery-Zwecke oder zum Testen von Applikationen nutzen möchten, können Sie eine Beziehung unterbrechen. Das Zielvolume wird in ein Lese- und Schreib-Volume geändert. Man kann keine SnapVault Beziehung durchbrechen. 
---
= Eine SnapMirror Beziehung von der Seite „Volume/Health Details“ abbrechen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Sicherungsbeziehung von der Seite Volume / Health Details brechen und die Datentransfers zwischen einem Quell- und Ziel-Volume in einer SnapMirror Beziehung stoppen. Wenn Sie Daten migrieren, für Disaster Recovery-Zwecke oder zum Testen von Applikationen nutzen möchten, können Sie eine Beziehung unterbrechen. Das Zielvolume wird in ein Lese- und Schreib-Volume geändert. Man kann keine SnapVault Beziehung durchbrechen.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.


.Schritte
. Wählen Sie auf der Registerkarte *Schutz* der Seite *Volumen / Gesundheit* Details aus der Topologie die SnapMirror Beziehung aus, die Sie brechen möchten.
. Klicken Sie mit der rechten Maustaste auf das Ziel und wählen Sie im Menü die Option *Pause* aus.
+
Das Dialogfeld Beziehung unterbrechen wird angezeigt.

. Klicken Sie auf *Weiter*, um die Beziehung zu brechen.
. Stellen Sie in der Topologie sicher, dass die Beziehung unterbrochen ist.

