---
permalink: data-protection/task_remove_protection_relationship.html 
sidebar: sidebar 
keywords: remove, protection, relationship, volume, relationships page 
summary: 'Auf der Seite Volume Relationships können Sie eine Schutzbeziehung entfernen, um eine vorhandene Beziehung zwischen der ausgewählten Quelle und dem ausgewählten Ziel dauerhaft zu löschen: Zum Beispiel, wenn Sie eine Beziehung unter Verwendung eines anderen Ziels erstellen möchten. Durch diesen Vorgang werden alle Metadaten entfernt und können nicht rückgängig gemacht werden.' 
---
= Entfernen einer Schutzbeziehung von der Seite Volume Relationships
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Volume Relationships können Sie eine Schutzbeziehung entfernen, um eine vorhandene Beziehung zwischen der ausgewählten Quelle und dem ausgewählten Ziel dauerhaft zu löschen: Zum Beispiel, wenn Sie eine Beziehung unter Verwendung eines anderen Ziels erstellen möchten. Durch diesen Vorgang werden alle Metadaten entfernt und können nicht rückgängig gemacht werden.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.


.Schritte
. Wählen Sie auf der Seite *Volume Relationships* ein oder mehrere Volumes mit Schutzbeziehungen aus, die Sie entfernen möchten, und klicken Sie in der Symbolleiste auf *Entfernen*.
+
Das Dialogfeld Beziehung entfernen wird angezeigt.

. Klicken Sie auf *Weiter*, um die Beziehung zu entfernen.
+
Die Beziehung wird von der Seite Volume Relationships entfernt.


