---
permalink: data-protection/task_create_snapmirror_relationship_with_version_flexible_replication.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, version-flexible, replication 
summary: Sie können eine SnapMirror Beziehung mit versionsflexibler Replizierung erstellen. Die versionsflexible Replizierung ermöglicht Ihnen die Implementierung der SnapMirror Sicherung, selbst wenn Quell- und Ziel-Volumes unter verschiedenen Versionen von ONTAP ausgeführt werden. 
---
= Erstellen einer SnapMirror Beziehung mit versionsflexibler Replizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SnapMirror Beziehung mit versionsflexibler Replizierung erstellen. Die versionsflexible Replizierung ermöglicht Ihnen die Implementierung der SnapMirror Sicherung, selbst wenn Quell- und Ziel-Volumes unter verschiedenen Versionen von ONTAP ausgeführt werden.

*Was Sie brauchen*

* Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.
* Die Quell- und Ziel-SVMs müssen jeweils eine SnapMirror Lizenz aktiviert haben.
* Die Quell- und Ziel-SVMs müssen jeweils unter einer Version von ONTAP ausgeführt werden, die eine versionsflexible Replizierung unterstützt.


SnapMirror mit versionsflexibler Replizierung ermöglicht Ihnen die Implementierung von SnapMirror Sicherung auch in heterogenen Storage-Umgebungen, in denen nicht der gesamte Storage unter einer Version von ONTAP läuft. Allerdings werden Spiegelvorgänge, die unter SnapMirror mit versionsflexibler Replizierung durchgeführt werden, nicht so schnell ausgeführt wie in herkömmlichen Blockreplizierung SnapMirror.

.Schritte
. Öffnen Sie das Dialogfeld *Schutz konfigurieren* für das zu schützenden Volume.
+
** Wenn Sie die Registerkarte Schutz der Seite Volume / Health Details anzeigen, klicken Sie mit der rechten Maustaste in die Topologieansicht, die den Namen eines Volumes hat, das Sie schützen möchten, und wählen Sie im Menü *Protect* > *SnapMirror* aus.
** Wenn Sie die Ansicht Health: All Volumes anzeigen, suchen Sie ein Volume, das Sie schützen möchten, und klicken Sie mit der rechten Maustaste darauf; wählen Sie dann aus dem Menü *schützen* > *SnapMirror*. Das Dialogfeld Schutz konfigurieren wird angezeigt.


. Klicken Sie auf *SnapMirror*, um die Registerkarte *SnapMirror* anzuzeigen.
. Füllen Sie im Dialogfeld *Schutz konfigurieren* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
+
Falls Sie eine Ziel-SVM angeben, die unter einer früheren Version von ONTAP ausgeführt wird als das zu schützende Quell-Volume. Falls diese frühere Version die versionsflexible Replizierung unterstützt, konfiguriert diese Aufgabe SnapMirror automatisch mit versionsflexibler Replizierung.

. Wenn Sie eine Ziel-SVM angeben, die unter derselben Version von ONTAP ausgeführt wird wie die des Quell-Volume, aber Sie dennoch SnapMirror mit versionsflexibler Replikation konfigurieren möchten, klicken Sie auf *Erweitert*, um die versionsflexible Replikation zu aktivieren und dann auf *Apply* zu klicken.
. Klicken Sie Auf *Anwenden*.
+
Sie gelangen zurück zur Seite Volume / Health Details.

. Klicken Sie oben auf der Seite *Volumen / Gesundheit* Details auf den Link für die Schutzkonfiguration.
+
Die Aufgaben und Details der Aufträge werden auf der Seite Job Details angezeigt.

. Klicken Sie auf der Seite *Job* Details auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und bestimmen Sie, wann der Job abgeschlossen ist.
. Wenn die Aufgaben abgeschlossen sind, klicken Sie auf *Zurück* in Ihrem Browser, um zur Detailseite *Volumen / Gesundheit* zurückzukehren.
+
Die neue Beziehung wird auf der Topologieansicht Volume / Health Details angezeigt.


